### ISSUE TITLE
Filling Out Existing Documentation

### ISSUE THREAD

**Issue by GaryPWhite** [wayfair-incubator/auxeng-docs#23]
We have many issues outlining incomplete or lacking documents currently available. Please use this super issue for general discussions, and assign yourself as you find issues you may want to take.

### Example engagement
- [x] #6 example engagement overview 
- [x] #20 Example engagement splash page
There will be more to do here -- but this issue focuses on existing docs, before worrying about writing new ones.

### Goals
- [x] #7 Goals with auxeng: how it should affect careers of those involved
- [x] #8 mobility for auxeng: goals on how it should affect career mobility for folks
- [x] #9 platforms: How auxeng can help platforms grow and learn and change
- [x] #21 goals splash page

### Running engagements
- [x] #10 expectations to set while running engagements
- [x] #11 following up with your cohort while running an engagement
- [x] #12 Iterating during your engagement, making it as effective as possible
- [x] #13 Facilitating a kickoff for an engagement
- [x] #14 Facilitating a planning session for an engagement
- [x] #15 Sourcing engagements
- [x] #16 What's next? what happens after the engagement ends?
- [x] #17 Wrapping up an engagement successfully
(noting that we're missing guidance on if engagements go wrong -- another thing we'll worry about later)

### Theory
- [ ] #18 Failure modes
- [ ] #19 Marketing
- [ ] #22 theory splash page

After we finish this -- we should expand documentation with more issues / superissues to track the effort.
